baseURL = "/"
languageCode = "en"
title = "WestGrid Webinars"
theme = "reveal-hugo"
footnotereturnlinkcontents = "↩"
relativeURLs = true
uglyURLs = true

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[params.reveal_hugo]
  load_default_plugins = false
  plugins = [
    "reveal-js/plugin/zoom-js/zoom.js",
    "reveal-js/plugin/notes/notes.js",
  ]
  # slide_number = 'c/t'
  controls = false
  # progress = true
  # controls_tutorial = false
  # controls_layout = 'bottom-left'
  transition = 'none'
  background_transition = 'none'

[params]
  favicon_32 = "/img/favicon.png"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.highlight]
    # codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # style = "manni"
    # style = "native"
    # style = "rainbow_dash"
    # style = "trac"
    style = "autumn"
    tabWidth = 4

pygmentsCodefencesGuessSyntax = true
pygmentsCodefences = true
# pygmentsUseClasses = true
